import Head from 'next/head'
import { Inter } from '@next/font/google';
import HeroSection from '../components/sections/HeroSection';
import NewsSection from '../components/sections/NewsSection';
import InformationSection from '../components/sections/InformationSection';
import ReasearchSection from '../components/sections/ReasearchSection';
import EventSection from '../components/sections/EventSection';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
     <HeroSection/>
      <NewsSection/>
      <InformationSection/>
      <ReasearchSection/>
      <EventSection/>
      </div>
    </>
  )
}
